# Generated by Django 4.1.4 on 2022-12-15 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('professional_email', models.EmailField(max_length=250)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('leetcode_handle', models.CharField(blank=True, max_length=50, null=True)),
                ('hackerrank_handle', models.CharField(blank=True, max_length=50, null=True)),
                ('hackerearth_handle', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
