# Generated by Django 4.1.4 on 2022-12-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_userprofile_github_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
