# Generated by Django 4.1.4 on 2022-12-28 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_alter_userprofile_linkedin_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='github_url',
            new_name='github_handle',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='linkedin_url',
            new_name='linkedin_handle',
        ),
    ]
