# Generated by Django 4.1.4 on 2022-12-31 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0003_alter_technologieslist_tech_logo'),
        ('user_profile', '0006_userprofile_tech_worked_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tech_worked_with',
            field=models.ManyToManyField(blank=True, to='technologies.technologieslist'),
        ),
    ]
