# Generated by Django 4.1.4 on 2022-12-31 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_alter_userprofile_tech_worked_with'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='tech_worked_with',
        ),
    ]
