# Generated by Django 4.1.4 on 2022-12-31 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0005_rename_github_url_userprofile_github_handle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologiesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_name', models.CharField(max_length=50)),
                ('tech_logo', models.ImageField(upload_to='tech_images')),
                ('belongs_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_profile.userprofile')),
            ],
        ),
    ]
