# Generated by Django 4.1.4 on 2022-12-31 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technologieslist',
            name='belongs_to',
        ),
    ]
