# Generated by Django 4.1.4 on 2022-12-31 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0002_remove_technologieslist_belongs_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologieslist',
            name='tech_logo',
            field=models.FileField(upload_to='tech_images'),
        ),
    ]
