# Generated by Django 4.1.4 on 2022-12-31 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_remove_userprofile_tech_worked_with'),
        ('technologies', '0003_alter_technologieslist_tech_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologieslist',
            name='known_by',
            field=models.ManyToManyField(blank=True, to='user_profile.userprofile'),
        ),
    ]
