# Generated by Django 4.1.4 on 2022-12-31 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0004_technologieslist_known_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technologieslist',
            name='known_by',
        ),
    ]
