# Generated by Django 4.1.4 on 2022-12-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_projects_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlist',
            name='project_link',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
