# Generated by Django 4.1.4 on 2022-12-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_projects_list', '0002_alter_projectlist_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlist',
            name='project_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
